AllCops:
  NewCops: enable
  UseCache: false
  Exclude:
     - 'db/**/*'
     - 'bin/**/*'
     - 'config/**/*'
     - 'config.ru'
     - 'spec/rails_helper.rb'
     - 'spec/spec_helper.rb'
     - 'spec/factories/*'
     - 'Rakefile'
     - 'lib/tasks/**/*'
     - 'app/controllers/panels_controller.rb'
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
Style/Documentation:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  Enabled: false
Layout:
  Max: 100
