AllCops:
  NewCops: enable
  UseCache: false
  Exclude:
     - 'db/**/*'
     - 'bin/**/*'
     - 'config/**/*'
     - 'config.ru'
     - 'spec/rails_helper.rb'
     - 'spec/spec_helper.rb'
     - 'spec/factories/*'
     - 'Rakefile'
     - 'lib/tasks/**/*'
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
Documentation:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  Enabled: false
Metrics/LineLength:
  Max: 100
