version: '3'
services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    environment:
      - PGHOST=${PG_HOST}
      - PGUSER=${PG_USER}
    volumes:
      - .:/protector-angels
    ports:
      - "3000:3000"
    depends_on:
      - db
      - sidekiq
      - redis
  sidekiq:
    build: .
    volumes:
      - .:/protector-angels
    command: bundle exec sidekiq
    depends_on:
      - redis
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - REDIS_URL=${REDIS_URL}
  redis:
    image: redis
