default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: oxossi12
development:
  <<: *default
  database: seven_facilities_development
test:
  <<: *default
  database: seven_facilities_test
production:
  <<: *default
  host: masud-test.postgres.uhserver.com
  database: masud_test
  username: masud_test
  password: '@@Oxossi12'
