class DeliveryTariff < ApplicationRecord
  validates :federative_unit,
            :kind,
            :destiny,
            :kg_1,
            :kg_2,
            :kg_3,
            :kg_4,
            :kg_5,
            :kg_6,
            :kg_7,
            :kg_8,
            :kg_9,
            :kg_10,
            :kg_11,
            :kg_12,
            :kg_13,
            :kg_14,
            :kg_15,
            :kg_16,
            :kg_17,
            :kg_18,
            :kg_19,
            :kg_20,
            :kg_21,
            :kg_22,
            :kg_23,
            :kg_24,
            :kg_25,
            :kg_26,
            :kg_27,
            :kg_28,
            :kg_29,
            :kg_30,
            :additional_kg,
            presence: { message: Messages.errors[:required_field] }

  validates :kg_1,
            :kg_2,
            :kg_3,
            :kg_4,
            :kg_5,
            :kg_6,
            :kg_7,
            :kg_8,
            :kg_9,
            :kg_10,
            :kg_11,
            :kg_12,
            :kg_13,
            :kg_14,
            :kg_15,
            :kg_16,
            :kg_17,
            :kg_18,
            :kg_19,
            :kg_20,
            :kg_21,
            :kg_22,
            :kg_23,
            :kg_24,
            :kg_25,
            :kg_26,
            :kg_27,
            :kg_28,
            :kg_29,
            :kg_30,
            :additional_kg,
            numericality: { greater_than: 0,
                            message: Messages.errors[:invalid_format] }
end
