# frozen_string_literal: true

class Place
  STATES_LIST = [%w[Acre Acre],
                 %w[Alagoas Alagoas],
                 %w[Amapá Amapá],
                 %w[Amazonas Amazonas],
                 %w[Bahia Bahia],
                 %w[Ceará Ceará],
                 ['Distrito Federal', 'Distrito Federal'],
                 ['Espírito Santo', 'Espírito Santo'],
                 %w[Goiás Goiás],
                 %w[Maranhão Maranhão],
                 ['Mato Grosso', 'Mato Grosso'],
                 ['Mato Grosso do Sul', 'Mato Grosso do Sul'],
                 ['Minas Gerais', 'Minas Gerais'],
                 %w[Paraná Paraná],
                 %w[Paraíba Paraíba],
                 %w[Pará Pará],
                 %w[Pernambuco Pernambuco],
                 %w[Piauí Piauí],
                 ['Rio Grande do Norte', 'Rio Grande do Norte'],
                 ['Rio Grande do Sul', 'Rio Grande do Sul'],
                 ['Rio de Janeiro', 'Rio de Janeiro'],
                 %w[Rondônia Rondônia],
                 %w[Roraima Roraima],
                 ['Santa Catarina', 'Santa Catarina'],
                 %w[Sergipe Sergipe],
                 ['São Paulo', 'São Paulo'],
                 %w[Tocantins Tocantins]].freeze
end
