class Place
  STATES_LIST = [["Acre", "Acre"],
    ["Alagoas", "Alagoas"],
    ["Amapá", "Amapá"],
    ["Amazonas", "Amazonas"],
    ["Bahia", "Bahia"],
    ["Ceará", "Ceará"],
    ["Distrito Federal", "Distrito Federal"],
    ["Espírito Santo", "Espírito Santo"],
    ["Goiás", "Goiás"],
    ["Maranhão", "Maranhão"],
    ["Mato Grosso", "Mato Grosso"],
    ["Mato Grosso do Sul", "Mato Grosso do Sul"],
    ["Minas Gerais", "Minas Gerais"],
    ["Paraná", "Paraná"],
    ["Paraíba", "Paraíba"],
    ["Pará", "Pará"],
    ["Pernambuco", "Pernambuco"],
    ["Piauí", "Piauí"],
    ["Rio Grande do Norte", "Rio Grande do Norte"],
    ["Rio Grande do Sul", "Rio Grande do Sul"],
    ["Rio de Janeiro", "Rio de Janeiro"],
    ["Rondônia", "Rondônia"],
    ["Roraima", "Roraima"],
    ["Santa Catarina", "Santa Catarina"],
    ["Sergipe", "Sergipe"],
    ["São Paulo", "São Paulo"],
    ["Tocantins", "Tocantins"]]
end
